# Generated by Django 5.1.2 on 2024-11-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_user', 'Can view user details'), ('can_create_user', 'Can create users'), ('can_edit_user', 'Can edit users'), ('can_delete_user', 'Can delete users')]},
        ),
    ]
